unit ObjFiles;

interface

procedure CGADriver;

procedure RUKA;
procedure TITUL;
procedure KAP1D;
procedure KAP1H;
procedure KAP2;
procedure KAP3;
procedure KAP4D;
procedure KAP4H;

procedure BEZVIKA;
procedure SVITI;
procedure OTEVRENA;

procedure BRYLE;
procedure DRAT;
procedure FEMUR;
procedure HAJZLPAP;
procedure JED;
procedure JEHLA;
procedure KLIC;
procedure LICIDLA;
procedure LUCERNA;
procedure MRTVOLA;
procedure OCI;
procedure OKO;
procedure OTVIRAK;
procedure PAVOUK;
procedure PAVUCINA;
procedure PILA;
procedure RAKEV;
procedure RECEPCNI;
procedure REDITEL;
procedure RUKAKLIC;
procedure SKLADNIK;
procedure SKRIN;
procedure SMETAK;
procedure STEHNA;
procedure UKLIZECK;
procedure ZILETKA;
procedure ZUB;
procedure ZUBY;


implementation

procedure CGADriver; external;
{$L OBJ\CGA.OBJ}

procedure RUKA; external;
{$L OBJ\RUKA.OBJ}

procedure TITUL; external;
{$L OBJ\TITUL.OBJ}

procedure KAP1D; external;
{$L OBJ\KAP1D.OBJ}

procedure KAP1H; external;
{$L OBJ\KAP1H.OBJ}

procedure KAP2; external;
{$L OBJ\KAP2.OBJ}

procedure KAP3; external;
{$L OBJ\KAP3.OBJ}

procedure KAP4D; external;
{$L OBJ\KAP4D.OBJ}

procedure KAP4H; external;
{$L OBJ\KAP4H.OBJ}

procedure BEZVIKA; external;
{$L OBJ\BEZVIKA.OBJ}

procedure SVITI; external;
{$L OBJ\SVITI.OBJ}

procedure OTEVRENA; external;
{$L OBJ\OTEVRENA.OBJ}

procedure BRYLE; external;
{$L OBJ\BRYLE.OBJ}

procedure DRAT; external;
{$L OBJ\DRAT.OBJ}

procedure FEMUR; external;
{$L OBJ\FEMUR.OBJ}

procedure HAJZLPAP; external;
{$L OBJ\HAJZLPAP.OBJ}

procedure JED; external;
{$L OBJ\JED.OBJ}

procedure JEHLA; external;
{$L OBJ\JEHLA.OBJ}

procedure KLIC; external;
{$L OBJ\KLIC.OBJ}

procedure LICIDLA; external;
{$L OBJ\LICIDLA.OBJ}

procedure LUCERNA; external;
{$L OBJ\LUCERNA.OBJ}

procedure MRTVOLA; external;
{$L OBJ\MRTVOLA.OBJ}

procedure OCI; external;
{$L OBJ\OCI.OBJ}

procedure OKO; external;
{$L OBJ\OKO.OBJ}

procedure OTVIRAK; external;
{$L OBJ\OTVIRAK.OBJ}

procedure PAVOUK; external;
{$L OBJ\PAVOUK.OBJ}

procedure PAVUCINA; external;
{$L OBJ\PAVUCINA.OBJ}

procedure PILA; external;
{$L OBJ\PILA.OBJ}

procedure RAKEV; external;
{$L OBJ\RAKEV.OBJ}

procedure RECEPCNI; external;
{$L OBJ\RECEPCNI.OBJ}

procedure REDITEL; external;
{$L OBJ\REDITEL.OBJ}

procedure RUKAKLIC; external;
{$L OBJ\RUKAKLIC.OBJ}

procedure SKLADNIK; external;
{$L OBJ\SKLADNIK.OBJ}

procedure SKRIN; external;
{$L OBJ\SKRIN.OBJ}

procedure SMETAK; external;
{$L OBJ\SMETAK.OBJ}

procedure STEHNA; external;
{$L OBJ\STEHNA.OBJ}

procedure UKLIZECK; external;
{$L OBJ\UKLIZECK.OBJ}

procedure ZILETKA; external;
{$L OBJ\ZILETKA.OBJ}

procedure ZUB; external;
{$L OBJ\ZUB.OBJ}

procedure ZUBY; external;
{$L OBJ\ZUBY.OBJ}

end.
