# -*- coding: utf-8 -*-

"""Script to generate codes used for decoding and displaying Czech
   characters by the `decode_and_write` Pascal procedure.
"""

import logging

import utils


def main():
    logging.basicConfig(level=logging.DEBUG, format='%(message)s')

    czech_chars = 'ÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž'

    codes = (utils.combine_from_pair(diacritic, letter)
             for diacritic, letter in utils.code_pairs(czech_chars))

    code_strings = ('${:02x}'.format(code) for code in codes)

    with open('../PUDR/KODY.PAS', 'w', encoding='ascii', newline='\r\n') as f:
        print('{generated by tools/generate_codes.py}\n', file=f)

        print(',\n'.join(code_strings), file=f)


if __name__ == '__main__':
    main()
